### ISSUE TITLE
Node embeddings extraction

### ISSUE THREAD

**Issue by mehrazi** [cjx96/UniCDR#1]
Hi,
I've tried to find your paper but I couldn't.
Anyway, I just tried to run the code with this command:
`CUDA_VISIBLE_DEVICES=1 python -u train_rec.py  --static_sample --cuda --domains game_video --task dual-user-inter --aggregator mean > dual_item_inter_game_video.log 2>&1&`
and everything went well.
My problem is to cluster users based on the telegram groups they have participated in, to handle this, I want to extract node embeddings from my graph and cluster them.
Is it possible with this repo? or do you have any recommendations?

**Comment by cjx96** [comment]
Ok, if you only have 1 domain user-item interaction data, you can put the preprocessed data in the right dataset directory [YOURDATA] first.

And then, run the following command:
CUDA_VISIBLE_DEVICES=1 python -u train_rec.py --static_sample --cuda --domains YOURDATA --task multi-user-intra --aggregator mean > multi_user_intra.log 2>&1&

If everything is right, you can derive the final user/item embedding at the evaluation stage (in Lines 218-219 of trainer.py, you should do some modifications) after the model is convergence.

At last, based on the learned user/item embedding, you can try some clustering algorithms.
