### ISSUE TITLE
数据集处理的问题

### ISSUE THREAD

**Issue by Geeker-LStar** [cjx96/UniCDR#7]
大佬好呀~~
我从 paper 中看到，您这篇论文的数据处理方法和 CDRIB 论文的处理方法是一样的。所以我下载了 CDRIB 中的数据预处理文件夹（[](https://github.com/cjx96/CDRIB/tree/main/dataset/preprocessing)），并用这个文件夹下的两个文件（先 filter 后 split）处理了我的 Amazon 数据集（和您使用的是一样的）。但是，我处理的结果却有点奇怪，如下图，它告诉我没有重叠的用户，但是我在您放在 CDRIB 上的仓库中看到是有重叠用户的：
![image](https://github.com/user-attachments/assets/dafb0c41-9671-4c58-910f-59d8a6fcb662)
另外，我自己用 Amazon 数据集弄了一个有重叠用户的（就是上一步不会报错的，具体的方法是从原始数据集比如 office 中选取 60% 作为域 A，选取另外 60% 作为域 B），但是在训练的时候遇到了报错，具体情况如下：
![image](https://github.com/user-attachments/assets/b9d8fb41-7c9c-4844-a986-663e732af6e7)

请问上面这两个问题可能是什么原因导致？如何解决？

谢谢大佬！！祝科研顺利!!!
❤.

**Comment by Geeker-LStar** [comment]
解决啦！

**Comment by jiayangniu** [comment]
> 解决啦！

请问您是如何解决的，我也遇见了相同问题

**Comment by jiayangniu** [comment]
解决了，从amazon下载的数据集item为第一列，user为第二列，所以需要修改两处代码:
ratings.columns = ['userId', 'itemId', 'Rating', 'timesteamp'] -->ratings.columns = ['itemId', 'userId', 'Rating', 'timesteamp']

data.append((dic_u[element[0]], dic_v[element[1]], 1))-> data.append((dic_u[element[1]], dic_v[element[0]], 1))
